project:
  project_crs: 3879
  datas_coverage_safety_percentage: 10
osm_network:
  osm_pbf_file_path: green_paths_2/src/cache/osm/hki_medium.osm.pbf
  original_crs: 4326
data_sources:
  - name: 'gvi_lines'
    filepath: green_paths_2/user/data/bike_network_with_gsv_landuse_green_index_FIXED/bikenetwork_with_gsv_landuse_green_index_FIXED.shp
    # data_type: vector
    data_column: Comb_GVI # mandatory
    no_data_value: 0
    min_data_value: 0.0 # mandatory
    max_data_value: 97.9 # mandatory
    good_exposure: True # mandatory
    # no_data_value: 999
    # data_buffer: 10 # optional, only for vector datas, in meters
    raster_cell_resolution: 10 # mandatory
    save_raster_file: True # optional
    original_crs: 3879


  # - name: "aqi"
  #   filepath: /Users/hcroope/Downloads/allPollutants_2024-05-29T16/allPollutants_2024-05-29T16.nc
  #   # filepath: green_paths_2/user/data/air_quality/allPollutants_2023-12-15T04.nc
  #   data_type: raster
  #   original_crs: 4326 # mandatory
  #   # layer_name: Helsinki_4326
  #   data_column: AQI  # mandatory
  #   # no_data_value: 999
  #   min_data_value: 1 # mandatory
  #   max_data_value: 5 # mandatory
  #   good_exposure: False # mandatory
  #   raster_cell_resolution: 10 # optional
  #   save_raster_file: True # optional
  #   custom_processing_function: convert_aq_nc_to_tif_and_scale_offset

  # - name: noise
  #   filepath:  green_paths_2/user/data/Helsinki_noise_data_2022/Melualueet_2022_01_kadut_maant_LAeq7-22_NPM_20231116_123645.gml # mandatory
  #   data_type: vector # mandatory
  #   raster_cell_resolution: 10 # mandatory -> this is the resolution of the raster cells in meters (e.g. 10 = 10mx10m)
  #   data_column: db_hi # mandatory
  #   no_data_value: 999
  #   min_data_value: 0.216 # mandatory
  #   max_data_value: 75 # mandatorya
  #   good_exposure: False # mandatory
  #   # columns_of_interest: ["db_hi", "geometry"] # optional
  #   original_crs: 3879 # optional
  #   raster_cell_resolution: 10 # optional
  #   save_raster_file: True # optional

routing:
    transport_mode: walking
    travel_speed: 5
    precalculate: False
    # transport_mode: cycling
    # origins: "/Users/hcroope/omat_playground/r5py/docs/_static/data/Helsinki/population_grid_2020.gpkg"
    # origins: "green_paths_2/user/data/data_random/origin_point.gpkg"
    
    
    # origins:   green_paths_2/user/data/data_random/100_ods_nort_london.gpkg


    # origins: green_paths_2/user/data/data_random/population_hki_centroids.gpkg
    # origins: green_paths_2/user/data/data_random/gothenburg_points.csv
    # origins: "green_paths_2/user/data/data_random/origins.csv"
    # origins: "green_paths_2/user/data/data_random/linnanmaki_origins.csv"
  
    # destinations: green_paths_2/user/data/data_random/destination_point.gpkg


    # origins: "green_paths_2/user/data/data_random/random_point_1.gpkg"
    # destinations: "green_paths_2/user/data/data_random/destinations_points.gpkg"


    # origins: green_paths_2/tests/data/od_pairs/test_hki_10_ods.gpkg
    # destinations: green_paths_2/tests/data/od_pairs/test_hki_10_ods.gpkg

    # origins: green_paths_2/user/data/data_random/HKI_200_ODS.gpkg
    # destinations: green_paths_2/user/data/data_random/HKI_200_ODS.gpkg

    # # TODO ROOPE TODO: aja tää sairas setti!
    # origins: green_paths_2/tests/data/od_pairs/mega_maggara_full_works.gpkg
    # destinations: green_paths_2/tests/data/od_pairs/mega_maggara_full_works.gpkg

    # AAPIIII

    origins: green_paths_2/src/API/temp_ods/api_origin.csv
    destinations: green_paths_2/src/API/temp_ods/api_destination.csv
    od_lon_name: lon
    od_lat_name: lat  
    od_crs: 4326

    # origins: green_paths_2/user/data/data_random/random_point_2.gpkg
    # destinations: green_paths_2/user/data/data_random/random_point_1.gpkg


    # origins: green_paths_2/tests/data/od_pairs/mega_gammara_testset.gpkg
    # destinations: green_paths_2/tests/data/od_pairs/mega_gammara_testset.gpkg


    # origins: green_paths_2/user/data/data_random/1000_ODS_NO_DUP_CENTROIDS.gpkg
    # destinations: green_paths_2/user/data/data_random/1000_ODS_NO_DUP_CENTROIDS.gpkg
 
    # destinations: green_paths_2/user/data/data_random/100_ods_nort_london.gpkg
    
    # destinations: "green_paths_2/user/data/data_random/destinations.csv"
    # destinations: green_paths_2/user/data/data_random/destinations_points_shp.shp
    # destinations: green_paths_2/user/data/data_random/population_hki_centroids.gpkg
    # destinations: green_paths_2/user/data/data_random/gothenburg_points.csv
    # od_crs: 27700
    exposure_parameters:
      - name: gvi_lines
        sensitivity: 1.5
      # - name: aqi
      #   sensitivity: 2.5
      # - name: noise
      #   sensitivity: 2.5

analysing:
  keep_geometry: True
  # save_output_name: roope_post_testi_elokuu
  # cumulative_ranges:
  #   gvi_lines:
  #     # - [0, 0.99]
  #     # - [1, 1.99]
  #     # - [2, 2.99]
  #     - [0,1]
  #     - [20, 50]
  #   aqi:
  #     - [0, 0.99]
  #     - [1, 1.99]
  #     - [2, 2.99]
  #     - [3, 3.99]
  #     - [4, 5]

