version: 2

build:
    os: ubuntu-22.04
    tools:
      python: "mambaforge-22.9"
    apt_packages:
        - default-jre

    conda:
      environment: environment.yml

    python:
      install:
        - method: pip
          path: .

    jobs:
      pre_install:
        - pip install
        - bash ./install_green_paths_2.sh
      # post_create_environment:
      #   # Install poetry
      #   - pip install poetry
      #   # Tell poetry to not use a virtual environment
      #   - poetry config virtualenvs.create false
      # post_install:
      #   # Install dependencies
      #   - poetry install --with docs

# python:
#     install:
#         - requirements: docs/requirements.txt

sphinx:
    configuration: docs/source/conf.py
    fail_on_warning: true


    