name: green_paths_2
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openjdk=21
  - gdal
  - fiona
  - numpy
  - pandas
  - pip
  - pip:
      - black==24.4.2
      - r5py@git+https://github.com/DigitalGeographyLab/r5py_gp2.git@gp2-no-list-conversion
      - sphinx
      - sphinx-rtd-theme
      - sphinx-autodoc-typehints