# Greetings traveller! This is the user's configuration file.
#

# TODO:  -> kirjota tää puhtaaks -> poista wanha


# The path to the OSM PBF file that you want to use. Path OR area should be specified, not both.
# if both are specified, the area will be ignored.

  # (primary) osm_pbf_file_path: this is the path to the osm pbf file. This will override area

  # TODO: : this was removed... but should it be added back?
  # osm_pbf_area: either name of the place e.g. Helsinki or the bbox coordinates e.g. 24.9,60.1,25.1,60.3
#
# The data sources are specified in a list called data_sources. 
# Each data source needs the following keys:
#
#   name: The name of the data source.
#
#   filepath: The path to the data source file. This can be either
#             an absolute path, or a path relative to the directory
#             containing the analysis configuration file.
#
#   type: The type of the data source. This can be one of the
#         following:
#
#         - vector: A vector data source. This can be any vector
#                   format supported by OMat, including GeoPackage,
#                   Shapefile, GeoJSON, and CSV.
#
#         - raster: A raster data source. This can be any raster
#                   format supported by OMat, including GeoPackage,
#                   GeoTIFF, and PNG.
#

# europe e.g. 3035


# project_crs: 27700

# hki
project_crs: 3879
# project_crs: 3006
datas_coverage_safety_percentage: 10
save_to_cache: True

osm_network:
  # osm_pbf_file_path: /Users/hcroope/omat/GP2/green_paths_2/green_paths_2/src/data/cache/london_osm_network.osm.pbf
  # osm_pbf_file_path: green_paths_2/src/cache/osm/hki_metropolitan_ish.osm.pbf

  # TODO: test whith this! 
  # helsinki metropolitan area from pyrosm
  # osm_pbf_file_path: green_paths_2/src/cache/osm/helsinki_network.osm.pbf

  # osm_pbf_file_path: /Users/hcroope/omat/GP2/green_paths_2/green_paths_2/green_paths_2/src/cache/osm/lintsi_pieni.osm.pbf

  osm_pbf_file_path: green_paths_2/src/cache/osm/hki_medium.osm.pbf

  # osm_pbf_file_path: green_paths_2/src/cache/osm/LONDON_OSM_100_AJA_TAA.osm.pbf

  # osm_pbf_file_path: green_paths_2/src/user/data/osm/hki_1000_all_roads.osm.pbf



  # osm_pbf_file_path: /Users/hcroope/omat/GP2/green_paths_2/green_paths_2/green_paths_2/src/cache/osm/joteborg_smaller.osm.pbf

  # osm_pbf_file_path: /Users/hcroope/Downloads/planet_-22.003,64.009_-21.652,64.193.osm.pbf


  # osm_pbf_file_path:   /Users/hcroope/omat/GP2/green_paths_2/green_paths_2/green_paths_2/src/cache/osm/joteborg_smaller.osm.pbf
  
  # osm_pbf_file_path: /Users/hcroope/omat/GP2/green_paths_2/green_paths_2/src/data/cache/helsinki_history_pbf_osm_network.osm.pbf
  original_crs: 4326
  filter_columns: ["id"]
  # segment_sampling_points_amount: 5

data_sources:

  # - name: shade
  #   filepath: /Users/hcroope/omat/GP2/data/robertin_shadow_reprojected.tif
  #   data_type: raster
  #   min_data_value: 0 # mandatory 
  #   max_data_value: 0.3333333432674408 # mandatory
  #   good_exposure: True # mandatory
  #   # original_crs: 3007
  #   # original_crs: 3879


  # - name: aqi_iceland
  #   filepath:   /Users/hcroope/omat/GP2/green_paths_2/green_paths_2/green_paths_2/src/user/data/nordicwelfair_nordic_emission_inventory_iceland.nc
  #   data_type: raster
  #   min_data_value: 0 # mandatory 
  #   max_data_value: 100 # mandatory
  #   good_exposure: True # mandatory
  #   original_crs: 3035
  #   custom_processing_function: convert_aq_nc_to_tif_and_scale_offset

  # - name: aqi_iceland_2
  #   filepath: /Users/hcroope/omat/GP2/green_paths_2/green_paths_2/green_paths_2/src/user/data/test_co_iceland_raster.tif
  #   data_type: raster
  #   min_data_value: 0 # mandatory 
  #   max_data_value: 100 # mandatory
  #   good_exposure: True # mandatory
  #   original_crs: 3035
  # custom_processing_function: convert_aq_nc_to_tif_and_scale_offset

  # - name: gvi
  #   filepath: green_paths_2/src/user/data/greenery/greenery_points.gpkg
  #   # data_type: vector
  #   layer_name: Helsinki_4326
  #   data_column: Gvi_Mean # mandatory
  #   no_data_value: 0
  #   min_data_value: 0.0096875 # mandatory
  #   max_data_value: 86.28875 # mandatory
  #   good_exposure: True # mandatory
  #   # data_buffer: 5 # optional, only for vector datas, in meters
  #   raster_cell_resolution: 10 # mandatory
  #   save_raster_file: True # optional
  #   original_crs: 3879

  - name: gvi_lines
    filepath: green_paths_2/src/user/data/bike_network_with_gsv_landuse_green_index_FIXED/bikenetwork_with_gsv_landuse_green_index_FIXED.shp
    # data_type: vector
    data_column: Comb_GVI # mandatory
    no_data_value: 0
    min_data_value: 0.0 # mandatory
    max_data_value: 97.9 # mandatorya
    good_exposure: True # mandatory
    # data_buffer: 10 # optional, only for vector datas, in meters
    raster_cell_resolution: 10 # mandatory
    save_raster_file: True # optional
    original_crs: 3879

  # - name: ndvi_london
  #   filepath: green_paths_2/src/user/data/greenery/London.tiff
  #   data_type: raster
  #   # data_column: Comb_GVI # mandatory
  #   no_data_value: 0
  #   min_data_value: -1.683009 # mandatory
  #   max_data_value: 2.15689 # mandatorya
  #   good_exposure: True # mandatory
  #   # data_buffer: 10 # optional, only for vector datas, in meters
  #   # raster_cell_resolution: 10 # mandatory
  #   save_raster_file: True # optional
  #   original_crs: 32630


  - name: aqi
    filepath: /Users/hcroope/Downloads/allPollutants_2024-05-29T16/allPollutants_2024-05-29T16.nc
    # filepath: green_paths_2/src/user/data/air_quality/allPollutants_2023-12-15T04.nc
    data_type: raster
    original_crs: 4326 # mandatory
    # layer_name: Helsinki_4326
    data_column: AQI  # mandatory
    no_data_value: 1
    min_data_value: 1 # mandatory
    max_data_value: 5 # mandatory
    good_exposure: False # mandatory
    raster_cell_resolution: 10 # optional
    save_raster_file: True # optional
    custom_processing_function: convert_aq_nc_to_tif_and_scale_offset

  # - name: noise
  #   filepath:  green_paths_2/src/user/data/Helsinki_noise_data_2022/Melualueet_2022_01_kadut_maant_LAeq7-22_NPM_20231116_123645.gml # mandatory
  #   data_type: vector # mandatory
  #   raster_cell_resolution: 10 # mandatory -> this is the resolution of the raster cells in meters (e.g. 10 = 10mx10m)
  #   data_column: db_hi # mandatory
  #   no_data_value: 0
  #   min_data_value: 0.216 # mandatory
  #   max_data_value: 75 # mandatorya
  #   good_exposure: False # mandatory
  #   # columns_of_interest: ["db_hi", "geometry"] # optional
  #   original_crs: 3879 # optional
  #   raster_cell_resolution: 10 # optional
  #   save_raster_file: True # optional

routing:
    # transport_mode: walking
    travel_speed: 15
    transport_mode: cycling
    # origins: "/Users/hcroope/omat_playground/r5py/docs/_static/data/Helsinki/population_grid_2020.gpkg"
    # origins: "green_paths_2/src/cache/data/origin_point.gpkg"
    
    origins: green_paths_2/src/cache/data/HKI_200_ODS.gpkg

    # origins: "green_paths_2/src/cache/data/random_point_1.gpkg"
    # origins:   green_paths_2/src/cache/data/100_ods_nort_london.gpkg
    # origins: green_paths_2/src/cache/data/1000_ODS_NO_DUP_CENTROIDS.gpkg
    
    # origins: green_paths_2/src/cache/data/population_hki_centroids.gpkg
    # origins: green_paths_2/src/cache/data/gothenburg_points.csv
    # origins: "green_paths_2/src/cache/data/origins.csv"
    # origins: "green_paths_2/src/cache/data/linnanmaki_origins.csv"
    # od_lon_name: longitude
    # od_lat_name: latitude
    # destinations: "green_paths_2/src/cache/data/destinations_points.gpkg"
    # destinations: green_paths_2/src/cache/data/destination_point.gpkg


    # destinations: green_paths_2/src/cache/data/1000_ODS_NO_DUP_CENTROIDS.gpkg
    destinations: green_paths_2/src/cache/data/HKI_200_ODS.gpkg

    # destinations: green_paths_2/src/cache/data/100_ods_nort_london.gpkg
    
    # destinations: "green_paths_2/src/cache/data/destinations.csv"
    # destinations: green_paths_2/src/cache/data/destinations_points_shp.shp
    # destinations: green_paths_2/src/cache/data/population_hki_centroids.gpkg
    # destinations: green_paths_2/src/cache/data/gothenburg_points.csv
    od_crs: 3879
    # od_crs: 27700
    exposure_parameters:
      - name: gvi_lines
        sensitivity: 2.5
      - name: aqi
        sensitivity: 2.5
      # - name: noise
      #   sensitivity: 2.5
      # - name: ndvi_london
      #   sensitivity: 5
      # - name: shade
      #   sensitivity: 2.5
      #   allow_missing_data: True


analysing:
  keep_geometry: True
  # batch_percentage: 50
  save_output_name: roope_results_test_gpkg_no_geom_iguess
  cumulative_ranges:
    gvi_lines:
      # - [0, 0.99]
      # - [1, 1.99]
      # - [2, 2.99]
      - [0,1]
      - [20, 50]
    aqi:
      - [0, 0.99]
      - [1, 1.99]
      - [2, 2.99]
      - [3, 3.99]
      - [4, 5]