name: Python Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of this workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        conda init bash
        source $HOME/miniconda/etc/profile.d/conda.sh  # Ensure conda is available

    - name: Set up Conda environment and install dependencies
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh  # Ensure conda is available
        conda create -n dgl_gp2 python=3.11 sqlite=3.41.1 -c conda-forge -y
        conda activate dgl_gp2
        conda install -c conda-forge gdal=3.6.4 openssl=3.0.9 -y  # Use a potentially more compatible GDAL and OpenSSL version
        pip install poetry
        poetry config virtualenvs.create false  # Ensure Poetry installs into the Conda environment
        poetry install --no-root  # Install dependencies but do not install the package itself
      shell: bash

    - name: Run tests
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh  # Ensure conda is available
        conda activate dgl_gp2
        pytest --version  # Verify pytest is installed
        poetry run pytest
      shell: bash
