name: Python Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of this workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        conda init bash
        source ~/.bashrc  # Reload the shell to apply conda initialization

    - name: Set up Conda environment and install GDAL
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh  # Ensure conda is available
        conda create -n dgl_gp2 python=3.11 -y
        conda activate dgl_gp2
        conda install -c conda-forge gdal  # Install GDAL and its dependencies
        pip install poetry
        poetry install
      shell: bash

    - name: Verify pytest installation and run tests
      run: |
        source $HOME/miniconda/etc/profile.d/conda.sh  # Ensure conda is available
        conda activate dgl_gp2
        pytest --version  # Verify pytest is installed
        poetry run pytest
      shell: bash